# Generated by Django 2.2 on 2019-04-28 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('company_url', models.CharField(blank=True, max_length=200)),
                ('posting_url', models.CharField(blank=True, max_length=200)),
                ('portal_url', models.CharField(blank=True, max_length=200)),
                ('portal_login', models.CharField(blank=True, max_length=50)),
                ('portal_pass', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField(blank=True)),
                ('posted_on', models.DateField(blank=True)),
                ('closes_on', models.DateField(blank=True)),
                ('applied_on', models.DateField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='user/')),
                ('cover_letter', models.FileField(blank=True, upload_to='user/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
