# Generated by Django 2.2 on 2019-05-13 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
